# Docker to Heroku Deployment
name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t kurt91932/wine_classification .

    - name: Login to Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: docker push kurt91932/wine_classification

      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:login

    - name: Deploy to Heroku
      run: heroku container:push web --app wine-classify
